# Generated by Django 6.0.1 on 2026-01-18 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emaillog_delivery_notification_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SullpierProfile',
            new_name='SupplierProfile',
        ),
    ]
