# Generated by Django 6.0.1 on 2026-01-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_order_alter_supplierprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='buy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='laptop', max_length=200),
            preserve_default=False,
        ),
    ]
