# Generated by Django 6.0.1 on 2026-02-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_description_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('Accepted', 'Accepted'), ('ASSIGNED', 'Assigned'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
